version: '3.8'

services:
#  kratos-service:
#    build: .
#    container_name: kratos-service
#    ports:
#      - "8000:8000"
#      - "9000:9000"
#    depends_on:
#      - db
#    environment:
#      - DATABASE_SOURCE=user:password@tcp(db:3306)/dbname?charset=utf8mb4&parseTime=True&loc=Local
#    networks:
#      - kratos-network

  db:
    image: mysql
    restart: "always"
    ports:
      - "12306:3306"
    # 账号密码
    environment:
      MYSQL_ROOT_PASSWORD: "12345678"
      MYSQL_DATABASE: "users"
    # 文件夹以及文件映射
    volumes:
      - "./mysql/data:/var/lib/mysql"
#    networks:
#      - kratos-network

#networks:
#  kratos-network:
#
#volumes:
#  db-data:
