// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/asynccnu/ccnu-service/internal/biz"
	"github.com/asynccnu/ccnu-service/internal/conf"
	"github.com/asynccnu/ccnu-service/internal/data"
	"github.com/asynccnu/ccnu-service/internal/registry"
	"github.com/asynccnu/ccnu-service/internal/server"
	"github.com/asynccnu/ccnu-service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, confRegistry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData)
	dataData, cleanup, err := data.NewData(confData, db)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData)
	userUsecase := biz.NewUserUsecase(userRepo)
	ccnuService := service.NewCCNUService(userUsecase)
	grpcServer := server.NewGRPCServer(confServer, ccnuService, logger)
	httpServer := server.NewHTTPServer(confServer, ccnuService, logger)
	etcdRegistry := registry.NewRegistrarServer(confRegistry, logger)
	app := newApp(logger, grpcServer, httpServer, etcdRegistry)
	return app, func() {
		cleanup()
	}, nil
}
