// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.6
// source: ccnu_service/v1/ccnu_service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CCNUService_SaveUser_FullMethodName  = "/api.ccnu_service.v1.CCNUService/SaveUser"
	CCNUService_GetCookie_FullMethodName = "/api.ccnu_service.v1.CCNUService/GetCookie"
)

// CCNUServiceClient is the client API for CCNUService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CCNUServiceClient interface {
	SaveUser(ctx context.Context, in *SaveUserRequest, opts ...grpc.CallOption) (*SaveUserResponse, error)
	GetCookie(ctx context.Context, in *GetCookieRequest, opts ...grpc.CallOption) (*GetCookieResponse, error)
}

type cCNUServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCCNUServiceClient(cc grpc.ClientConnInterface) CCNUServiceClient {
	return &cCNUServiceClient{cc}
}

func (c *cCNUServiceClient) SaveUser(ctx context.Context, in *SaveUserRequest, opts ...grpc.CallOption) (*SaveUserResponse, error) {
	out := new(SaveUserResponse)
	err := c.cc.Invoke(ctx, CCNUService_SaveUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cCNUServiceClient) GetCookie(ctx context.Context, in *GetCookieRequest, opts ...grpc.CallOption) (*GetCookieResponse, error) {
	out := new(GetCookieResponse)
	err := c.cc.Invoke(ctx, CCNUService_GetCookie_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CCNUServiceServer is the server API for CCNUService service.
// All implementations must embed UnimplementedCCNUServiceServer
// for forward compatibility
type CCNUServiceServer interface {
	SaveUser(context.Context, *SaveUserRequest) (*SaveUserResponse, error)
	GetCookie(context.Context, *GetCookieRequest) (*GetCookieResponse, error)
	mustEmbedUnimplementedCCNUServiceServer()
}

// UnimplementedCCNUServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCCNUServiceServer struct {
}

func (UnimplementedCCNUServiceServer) SaveUser(context.Context, *SaveUserRequest) (*SaveUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveUser not implemented")
}
func (UnimplementedCCNUServiceServer) GetCookie(context.Context, *GetCookieRequest) (*GetCookieResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCookie not implemented")
}
func (UnimplementedCCNUServiceServer) mustEmbedUnimplementedCCNUServiceServer() {}

// UnsafeCCNUServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CCNUServiceServer will
// result in compilation errors.
type UnsafeCCNUServiceServer interface {
	mustEmbedUnimplementedCCNUServiceServer()
}

func RegisterCCNUServiceServer(s grpc.ServiceRegistrar, srv CCNUServiceServer) {
	s.RegisterService(&CCNUService_ServiceDesc, srv)
}

func _CCNUService_SaveUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CCNUServiceServer).SaveUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CCNUService_SaveUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CCNUServiceServer).SaveUser(ctx, req.(*SaveUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CCNUService_GetCookie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCookieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CCNUServiceServer).GetCookie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CCNUService_GetCookie_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CCNUServiceServer).GetCookie(ctx, req.(*GetCookieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CCNUService_ServiceDesc is the grpc.ServiceDesc for CCNUService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CCNUService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.ccnu_service.v1.CCNUService",
	HandlerType: (*CCNUServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveUser",
			Handler:    _CCNUService_SaveUser_Handler,
		},
		{
			MethodName: "GetCookie",
			Handler:    _CCNUService_GetCookie_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ccnu_service/v1/ccnu_service.proto",
}
